### ISSUE TITLE
[BUG] não atualiza no startup :((((

### ISSUE THREAD

**Issue by GuiRojas** [GuiBrandt/god#4]
a tela de "deseja atualizar [Y/N]" aparece como usual, porém da erro  
[versão 2.0.0]

https://imgur.com/a/1H09gQI

é isso
plz fix

**Comment by GuiBrandt** [comment]
Faltou o `error.log`, não dá pra entender o que acontece só pela print.

Also, não é pra ser a versão 2.0.0, porque não tem atualização nessa versão :L

Pelo que a gente discutiu no discord, deve ser problema no arquivo `god/version.py` que tá dando problema se não tiver um `.version` na pasta do god. Também é por isso que ele mostra a versão como `v2.0.0` enquanto é pra estar na `v2.1.0` no mínimo. Vou dar uma olhada nisso.

Por enquanto, rodar isso pelo `cmd` na pasta do God deve resolver o problema:

    echo v2.1.0-beta > .version

**Comment by GuiBrandt** [comment]
Arrumado em 81b88d1
